//Globals
let time = 5;
let score = 0;
let isPlaying;

const wordInput = document.querySelector("#word-input");
const currentWord = document.querySelector("#current-word");
const scoreDisplay = document.querySelector("#score");
const timeDisplay = document.querySelector("#time");
const message = document.querySelector("#message");
const seconds = document.querySelector("#seconds");

const words = [
  "pig",
  "andouille",
  "pastrami",
  "prosciutto",
  "ground",
  "round",
  "jowl",
  "beef",
  "ribs",
  "alcatra",
  "frankfurter.",
  "Tail",
  "boudin",
  "porchetta,",
  "tongue",
  "jowl",
  "shankle",
  "pastrami",
  "chuck",
  "shoulder",
  "turducken",
  "sirloin",
  "frankfurter.",
  "Ground",
  "round",
  "chuck",
  "beef,",
  "burgdoggen",
  "frankfurter",
  "turducken",
  "pork",
  "cow.",
  "Hamburger",
  "t-bone",
  "pork",
  "loin",
  "ham",
  "chicken",
  "meatball",
  "shank.",
  "Sirloin",
  "short",
  "ribs",
  "meatloaf",
  "biltong",
  "burgdoggen",
  "capicola",
  "tenderloin",
  "bresaola",
  "tongue.",
  "Ground",
  "round",
  "corned",
  "beef",
  "salami,",
  "pork",
  "alcatra",
  "buffalo",
  "beef",
  "doner",
  "tongue.",
  "Boudin",
  "tail",
  "kielbasa",
  "shankle.",
  "Tri-tip",
  "meatball",
  "t-bone",
  "doner",
  "pork",
  "loin",
  "andouille.",
  "Leberkas",
  "biltong",
  "spare",
  "ribs",
  "pork",
  "loin",
  "frankfurter",
  "jowl,",
  "beef",
  "buffalo",
  "ground",
  "round",
  "andouille",
  "rump",
  "tongue",
  "pork",
  "bresaola.",
  "Kielbasa",
  "chicken",
  "tri-tip,",
  "pig",
  "prosciutto",
  "landjaeger",
  "swine",
  "bresaola",
  "brisket",
  "frankfurter",
  "tongue",
  "porchetta",
  "cupim"
];

//Initialize Game
function init() {
  console.log("init");
}
